alias bld="make && sudo make clean install"
alias cl="clear"
alias cp="cp -iv"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias ka="killall"
alias l="exa -la"
alias ll="ls -A"
alias ls="ls -hNv --color=auto --group-directories-first"
alias mkd="mkdir -pv"
alias mv="mv -iv"
alias p="sudo pacman"
alias rm="rm -vI"
alias rmln="find . -xtype l -delete"
alias startx="startx $XDG_CONFIG_HOME/X11/xinitrc"

# Apps
alias r="$FILE"
alias sr="sudo $FILE"
alias v="$EDITOR"
alias sv="sudo $EDITOR"
