alias cfa="$EDITOR ~/.config/zsh/custom/alias/alias.zsh"
alias cfg="$EDITOR ~/.config/zsh/custom/alias/git.zsh"
alias cfd="$EDITOR ~/.config/zsh/custom/alias/dirs.zsh"
alias cff="$EDITOR ~/.config/zsh/custom/alias/files.zsh"
alias cblo="cd ~/.local/src/dwmblocks && $EDITOR blocks.h"
alias cdwm="cd ~/.local/src/dwm && $EDITOR config.h"
