#!/bin/sh

aurhelper=paru

get_user_and_pass() {
	name=$(dialog --inputbox "First, please enter a name for the user account." 10 60 3>&1 1>&2 2>&3 3>&1) || exit 1
	while ! echo "$name" | grep -q "^[a-z_][a-z0-9_-]*$"; do
		name=$(dialog --no-cancel --inputbox "Username not valid. Give a username beginning with a letter, with only lowercase letters, - or _." 10 60 3>&1 1>&2 2>&3 3>&1)
	done
	pass1=$(dialog --no-cancel --passwordbox "Enter a password for that user." 10 60 3>&1 1>&2 2>&3 3>&1)
	pass2=$(dialog --no-cancel --passwordbox "Retype password." 10 60 3>&1 1>&2 2>&3 3>&1)
	while ! [ "$pass1" = "$pass2" ]; do
		unset pass2
		pass1=$(dialog --no-cancel --passwordbox "Passwords do not match.\\n\\nEnter password again." 10 60 3>&1 1>&2 2>&3 3>&1)
		pass2=$(dialog --no-cancel --passwordbox "Retype password." 10 60 3>&1 1>&2 2>&3 3>&1)
	done ;}

get_mail() {
	mail1=$(dialog --inputbox "Enter your email." 10 60 3>&1 1>&2 2>&3 3>&1)
	mail2=$(dialog --inputbox "Retype your email." 10 60 3>&1 1>&2 2>&3 3>&1)
	while ! [ "$mail1" = "$mail2" ]; do
		unset mail2
		mail1=$(dialog --inputbox "Mails do not match.\\n\\nEnter your email again." 10 60 3>&1 1>&2 2>&3 3>&1)
		mail2=$(dialog --inputbox "Retype your email." 10 60 3>&1 1>&2 2>&3 3>&1)
	done
  export email=$mail1 ;}

adduserandpass() {
	dialog --infobox "Adding user \"$name\"..." 4 50
	useradd -mg wheel "$name" >/dev/null 2>&1 ||
	usermod -aG wheel,audio,video,optical,storage,libvirt "$name"
	echo "$name:$pass1" | chpasswd
	unset pass1 pass2 ;}

install_aur_helper() {
  cd /tmp
  curl -sO https://aur.archlinux.org/cgit/aur.git/snapshot/"$aurhelper".tar.gz
  tar -xvf "$aurhelper".tar.gz
  cd "$aurhelper"
  makepkg --noconfirm -si
  sudo rm -rf ../$aurhelper*
  cd ~
}

# Create user
get_user_and_pass
get_mail
adduserandpass
pacman -S sudo
echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers
su $name

# Install packages
sudo pacman -S --needed $(comm -12 <(pacman -Slq | sort) <(sort backup/arch/pac.list ))
install_aur_helper
$aurhelper -S --needed $(comm -12 <(yay -Slq | sort) <(sort backup/arch/aur.list ))

# Clone dotfiles repo
git clone https://github.com/martinsione/dotfiles.git ~/dotfiles

mkdir -p ~/.config/VSCodium/User ~/.local
cd ~/dotfiles
stow src

# Compile packages
for file in ~/.local/src/*; do cd "$file" && make && sudo make clean install; done

# Change shell to zsh
chsh -s $(which zsh)
source ~/.config/zsh/.zshrc

# Install git programs
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Auto mount the hard drive
# echo 'UUID=0492de4e-821d-48d4-970f-7a7ccb869fe0	/mnt/storage	ext4		rw,relatime	0 2' | sudo tee -a /etc/fstab
echo 'export ZDOTDIR=$HOME/.config/zsh' | sudo tee -a /etc/zsh/zshenv

# Generate ssh keys
# ssh-keygen -t rsa -b 4096 -C "${email}"
# eval "$(ssh-agent -s)"
# ssh-add ~/.ssh/id_rsa
