local M = {}

function M.get(c)
	-- stylua: ignore
	return {
		-- Editor
		Normal           = { fg = c.fg, bg = c.bg },
		NormalFloat      = { fg = c.fg, bg = c.bg_dark },
		NormalNC         = { fg = c.fg, bg = c.bg },
		Cursor           = { fg = c.bg, bg = c.fg },
		CursorLine       = { bg = c.bg_highlight },
		CursorLineNr     = { fg = c.fg, bold = true },
		LineNr           = { fg = c.fg_dark },
		SignColumn        = { fg = c.fg_dark, bg = c.bg },
		FoldColumn       = { fg = c.fg_dark, bg = c.bg },
		ColorColumn      = { bg = c.bg_highlight },
		Folded           = { fg = c.fg_muted, bg = c.bg_highlight },
		Visual           = { bg = c.bg_visual },
		VisualNOS        = { bg = c.bg_visual },
		Search           = { fg = c.bg, bg = c.blue },
		IncSearch        = { fg = c.bg, bg = c.orange },
		CurSearch        = { fg = c.bg, bg = c.orange },
		Substitute       = { fg = c.bg, bg = c.pink },
		Pmenu            = { fg = c.fg, bg = c.bg_dark },
		PmenuSel         = { bg = c.bg_highlight },
		PmenuSbar        = { bg = c.bg_element },
		PmenuThumb       = { bg = c.fg_muted },
		StatusLine       = { fg = c.fg, bg = c.bg_dark },
		StatusLineNC     = { fg = c.fg_muted, bg = c.bg_dark },
		TabLine          = { fg = c.fg_muted, bg = c.bg_dark },
		TabLineFill      = { bg = c.bg_dark },
		TabLineSel       = { fg = c.fg, bg = c.bg },
		WinBar           = { fg = c.fg, bg = c.bg },
		WinBarNC         = { fg = c.fg_muted, bg = c.bg },
		WinSeparator     = { fg = c.border },
		VertSplit        = { fg = c.border },
		FloatBorder      = { fg = c.border, bg = c.bg_dark },
		FloatTitle       = { fg = c.fg, bg = c.bg_dark },
		NonText          = { fg = c.border },
		SpecialKey       = { fg = c.border },
		Whitespace       = { fg = c.border },
		MatchParen       = { fg = c.orange, bold = true },
		Directory        = { fg = c.blue },
		Title            = { fg = c.blue, bold = true },
		Question         = { fg = c.blue },
		MoreMsg          = { fg = c.blue },
		ModeMsg          = { fg = c.fg_muted },
		ErrorMsg         = { fg = c.pink },
		WarningMsg       = { fg = c.orange },
		Conceal          = { fg = c.fg_muted },
		WildMenu         = { bg = c.bg_visual },
		SpellBad         = { sp = c.pink, undercurl = true },
		SpellCap         = { sp = c.orange, undercurl = true },
		SpellLocal       = { sp = c.blue, undercurl = true },
		SpellRare        = { sp = c.purple, undercurl = true },

		-- Diff
		DiffAdd          = { bg = c.diff_add },
		DiffChange       = { bg = c.diff_change },
		DiffDelete       = { bg = c.diff_delete },
		DiffText         = { bg = c.diff_text },

		-- Syntax
		Comment        = { fg = c.fg_muted, italic = true },
		Constant       = { fg = c.blue },
		String         = { fg = c.green },
		Character      = { fg = c.green },
		Number         = { fg = c.blue },
		Boolean        = { fg = c.blue },
		Float          = { fg = c.blue },
		Identifier     = { fg = c.fg },
		Function       = { fg = c.purple },
		Statement      = { fg = c.pink },
		Conditional    = { fg = c.pink },
		Repeat         = { fg = c.pink },
		Label          = { fg = c.blue },
		Operator       = { fg = c.pink },
		Keyword        = { fg = c.pink },
		Exception      = { fg = c.pink },
		PreProc        = { fg = c.pink },
		Include        = { fg = c.pink },
		Define         = { fg = c.pink },
		Macro          = { fg = c.pink },
		PreCondit      = { fg = c.pink },
		Type           = { fg = c.purple },
		StorageClass   = { fg = c.pink },
		Structure      = { fg = c.purple },
		Typedef        = { fg = c.purple },
		Special        = { fg = c.blue },
		SpecialChar    = { fg = c.green },
		Tag            = { fg = c.green },
		Delimiter      = { fg = c.fg_muted },
		SpecialComment = { fg = c.fg_muted },
		Debug          = { fg = c.pink },
		Underlined     = { underline = true },
		Bold           = { bold = true },
		Italic         = { italic = true },
		Error          = { fg = c.pink },
		Todo           = { fg = c.orange, bold = true },

		-- Treesitter
		["@variable"]               = { fg = c.fg },
		["@variable.builtin"]       = { fg = c.blue },
		["@variable.parameter"]     = { fg = c.fg },
		["@variable.member"]        = { fg = c.blue },
		["@constant"]               = { fg = c.blue },
		["@constant.builtin"]       = { fg = c.blue },
		["@constant.macro"]         = { fg = c.blue },
		["@module"]                 = { fg = c.fg },
		["@label"]                  = { fg = c.blue },
		["@string"]                 = { fg = c.green },
		["@string.escape"]          = { fg = c.green },
		["@string.regexp"]          = { fg = c.green },
		["@string.special"]         = { fg = c.green },
		["@string.special.symbol"]  = { fg = c.green },
		["@character"]              = { fg = c.green },
		["@character.special"]      = { fg = c.green },
		["@boolean"]                = { fg = c.blue },
		["@number"]                 = { fg = c.blue },
		["@number.float"]           = { fg = c.blue },
		["@type"]                   = { fg = c.purple },
		["@type.builtin"]           = { fg = c.purple },
		["@type.definition"]        = { fg = c.purple },
		["@attribute"]              = { fg = c.purple },
		["@property"]               = { fg = c.blue },
		["@function"]               = { fg = c.purple },
		["@function.builtin"]       = { fg = c.purple },
		["@function.call"]          = { fg = c.purple },
		["@function.macro"]         = { fg = c.purple },
		["@function.method"]        = { fg = c.purple },
		["@function.method.call"]   = { fg = c.purple },
		["@constructor"]            = { fg = c.green },
		["@operator"]               = { fg = c.pink },
		["@keyword"]                = { fg = c.pink },
		["@keyword.coroutine"]      = { fg = c.pink },
		["@keyword.function"]       = { fg = c.pink },
		["@keyword.operator"]       = { fg = c.pink },
		["@keyword.import"]         = { fg = c.pink },
		["@keyword.type"]           = { fg = c.pink },
		["@keyword.modifier"]       = { fg = c.pink },
		["@keyword.repeat"]         = { fg = c.pink },
		["@keyword.return"]         = { fg = c.pink },
		["@keyword.exception"]      = { fg = c.pink },
		["@keyword.conditional"]    = { fg = c.pink },
		["@keyword.directive"]      = { fg = c.pink },
		["@punctuation.delimiter"]  = { fg = c.fg_muted },
		["@punctuation.bracket"]    = { fg = c.fg_muted },
		["@punctuation.special"]    = { fg = c.pink },
		["@comment"]                = { fg = c.fg_muted, italic = true },
		["@comment.documentation"]  = { fg = c.fg_muted, italic = true },
		["@comment.error"]          = { fg = c.pink, italic = true },
		["@comment.warning"]        = { fg = c.orange, italic = true },
		["@comment.todo"]           = { fg = c.orange, italic = true },
		["@comment.note"]           = { fg = c.blue, italic = true },
		["@markup.strong"]          = { bold = true },
		["@markup.italic"]          = { italic = true },
		["@markup.strikethrough"]   = { strikethrough = true },
		["@markup.underline"]       = { underline = true },
		["@markup.heading"]         = { fg = c.blue, bold = true },
		["@markup.quote"]           = { fg = c.fg_muted, italic = true },
		["@markup.math"]            = { fg = c.blue },
		["@markup.link"]            = { fg = c.blue, underline = true },
		["@markup.link.label"]      = { fg = c.blue },
		["@markup.link.url"]        = { fg = c.blue, underline = true },
		["@markup.raw"]             = { fg = c.green },
		["@markup.list"]            = { fg = c.pink },
		["@diff.plus"]              = { fg = c.green },
		["@diff.minus"]             = { fg = c.pink },
		["@diff.delta"]             = { fg = c.orange },
		["@tag"]                    = { fg = c.green },
		["@tag.attribute"]          = { fg = c.purple },
		["@tag.delimiter"]          = { fg = c.fg_muted },

		-- LSP semantic tokens
		["@lsp.type.class"]         = { fg = c.purple },
		["@lsp.type.decorator"]     = { fg = c.purple },
		["@lsp.type.enum"]          = { fg = c.purple },
		["@lsp.type.enumMember"]    = { fg = c.blue },
		["@lsp.type.function"]      = { fg = c.purple },
		["@lsp.type.interface"]     = { fg = c.purple },
		["@lsp.type.macro"]         = { fg = c.pink },
		["@lsp.type.method"]        = { fg = c.purple },
		["@lsp.type.namespace"]     = { fg = c.fg },
		["@lsp.type.parameter"]     = { fg = c.fg },
		["@lsp.type.property"]      = { fg = c.blue },
		["@lsp.type.struct"]        = { fg = c.purple },
		["@lsp.type.type"]          = { fg = c.purple },
		["@lsp.type.typeParameter"] = { fg = c.purple },
		["@lsp.type.variable"]      = { fg = c.fg },

		-- Diagnostics
		DiagnosticError              = { fg = c.pink },
		DiagnosticWarn               = { fg = c.orange },
		DiagnosticInfo               = { fg = c.blue },
		DiagnosticHint               = { fg = c.fg_muted },
		DiagnosticVirtualTextError   = { fg = c.pink, bg = c.error_bg },
		DiagnosticVirtualTextWarn    = { fg = c.orange, bg = c.warn_bg },
		DiagnosticVirtualTextInfo    = { fg = c.blue, bg = c.info_bg },
		DiagnosticVirtualTextHint    = { fg = c.fg_muted, bg = c.hint_bg },
		DiagnosticUnderlineError     = { sp = c.pink, undercurl = true },
		DiagnosticUnderlineWarn      = { sp = c.orange, undercurl = true },
		DiagnosticUnderlineInfo      = { sp = c.blue, undercurl = true },
		DiagnosticUnderlineHint      = { sp = c.fg_muted, undercurl = true },

		-- LSP references
		LspReferenceText  = { bg = c.bg_highlight },
		LspReferenceRead  = { bg = c.bg_highlight },
		LspReferenceWrite = { bg = c.bg_highlight },
		LspInlayHint      = { fg = c.fg_dark, italic = true },

		-- GitSigns
		GitSignsAdd    = { fg = c.green },
		GitSignsChange = { fg = c.orange },
		GitSignsDelete = { fg = c.pink },

		-- Telescope
		TelescopeNormal       = { fg = c.fg, bg = c.bg_dark },
		TelescopeBorder       = { fg = c.border, bg = c.bg_dark },
		TelescopePromptNormal = { fg = c.fg, bg = c.bg_element },
		TelescopePromptBorder = { fg = c.bg_element, bg = c.bg_element },
		TelescopePromptTitle  = { fg = c.bg, bg = c.blue },
		TelescopePreviewTitle = { fg = c.bg, bg = c.green },
		TelescopeResultsTitle = { fg = c.bg_dark, bg = c.bg_dark },
		TelescopeSelection    = { bg = c.bg_highlight },
		TelescopeMatching     = { fg = c.blue, bold = true },

		-- NeoTree
		NeoTreeNormal        = { fg = c.fg, bg = c.bg_dark },
		NeoTreeNormalNC      = { fg = c.fg, bg = c.bg_dark },
		NeoTreeDimText       = { fg = c.fg_muted },
		NeoTreeGitAdded      = { fg = c.green },
		NeoTreeGitModified   = { fg = c.orange },
		NeoTreeGitDeleted    = { fg = c.pink },
		NeoTreeGitUntracked  = { fg = c.fg_muted },
		NeoTreeIndentMarker  = { fg = c.border },
		NeoTreeFileName      = { fg = c.fg },
		NeoTreeDirectoryName = { fg = c.blue },
		NeoTreeDirectoryIcon = { fg = c.blue },
		NeoTreeRootName      = { fg = c.blue, bold = true },

		-- Lazy
		LazyNormal       = { fg = c.fg, bg = c.bg_dark },
		LazyButton       = { fg = c.fg, bg = c.bg_element },
		LazyButtonActive = { fg = c.fg, bg = c.bg_highlight },

		-- Mason
		MasonNormal = { fg = c.fg, bg = c.bg_dark },
	}
end

return M
