column_limit: 100
indent_width: 2
continuation_indent_width: 2
keep_simple_control_block_one_line: true
keep_simple_function_one_line: true
double_quote_to_single_quote: true
extra_sep_at_table_end: true
chop_down_table: true
