##
## -- Settings --
##
set -g base-index 1               # start windows numbering at 1
set -g default-terminal "screen-256color"
set -g mode-keys vi               # vim like keys
set -g mouse on                   # Enable mouse
set -g pane-base-index 1          # make pane numbering consistent with windows
# set -g pane-border-format "#P: #{pane_current_path}"
# set -g pane-border-status top # off|top|bottom
set -g renumber-windows on        # renumber windows when a window is closed
set -g set-titles on
set -g status-bg black
set -g status-fg white
set -g status-right "%R %d-%h-%y"

##
## -- Mappings --
##
set -g prefix C-a

bind c new-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind V split-window -c "#{pane_current_path}"

## Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind r command-prompt -I "#{window_name}" "rename-window '%%'"

## Reload configuration
bind R source-file ~/.config/tmux/tmux.conf \; display 'tmux.conf sourced'

